# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fase1.1ssii.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio(object):
  
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(1120, 880)
        Inicio.setMaximumSize(QtCore.QSize(1120, 887))
        self.centralwidget = QtWidgets.QWidget(Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 50, 421, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 1021, 111))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 210, 421, 421))
        self.label_3.setObjectName("label_3")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(80, 710, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(890, 700, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        Inicio.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Inicio)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        self.menuInicio = QtWidgets.QMenu(self.menubar)
        self.menuInicio.setObjectName("menuInicio")
        Inicio.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Inicio)
        self.statusbar.setObjectName("statusbar")
        Inicio.setStatusBar(self.statusbar)
        self.actionInicio = QtWidgets.QAction(Inicio)
        self.actionInicio.setObjectName("actionInicio")
        self.actionB_squeda = QtWidgets.QAction(Inicio)
        self.actionB_squeda.setObjectName("actionB_squeda")
        self.actionSimilitud = QtWidgets.QAction(Inicio)
        self.actionSimilitud.setObjectName("actionSimilitud")
        self.menuInicio.addAction(self.actionInicio)
        self.menuInicio.addAction(self.actionB_squeda)
        self.menuInicio.addAction(self.actionSimilitud)
        self.menubar.addAction(self.menuInicio.menuAction())

        self.retranslateUi(Inicio)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        Inicio.setWindowTitle(_translate("Inicio", "BarbeitoS"))
        self.label.setText(_translate("Inicio", "BIENVENIDO A LA APLICACIÓN"))
        self.label_2.setText(_translate("Inicio", "En esta aplicación se le ofrece la búsqueda de noticias sobre una amplia variedad, así como la posibilidad de comprar las mismas."))
        self.label_3.setText(_translate("Inicio", "<html><head/><body><p><img src=\":/prefijoNuevo/app.jpg\"/></p></body></html>"))
        self.commandLinkButton.setText(_translate("Inicio", "BÚSQUEDA"))
        self.commandLinkButton_2.setText(_translate("Inicio", "SIMILITUD"))
        self.menuInicio.setTitle(_translate("Inicio", "Navegación"))
        self.actionInicio.setText(_translate("Inicio", "Inicio"))
        self.actionB_squeda.setText(_translate("Inicio", "Búsqueda"))
        self.actionSimilitud.setText(_translate("Inicio", "Similitud"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inicio = QtWidgets.QMainWindow()
    ui = Ui_Inicio()
    ui.setupUi(Inicio)
    Inicio.show()
    sys.exit(app.exec_())
